<a href="https://colab.research.google.com/github/Thanchanya309/PythonDataViz2026/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HW 5 เขียน function คูณ matrix

แล้ว test กับ matrix ขนาด

- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)

In [3]:
import numpy as np

In [1]:
def mat_mul(A,B):
    C = np.zeros((A.shape[0],B.shape[1])) #เตรียมขนาดของ matrix ผลลัพธ์ แถวเท่ากับตัวหน้า หลักเท่ากับตัวหลัง
    for r_a in range(A.shape[0]): # ซนลูปไล่ไปตามแถวของตัวหน้า
        for c_b in range(B.shape[1]): #วนลูปไล่ไปตามหลัก
            for every_element in range(A.shape[1]):
                C[r_a,c_b] = C[r_a,c_b] + (A[r_a,every_element] * B[every_element,c_b])
                # ตรงตัว c เป็นการบอกว่าผลคูณที่ได้ จะได้มาจากการจับคูณกันโดยตัวของแถวแรกตัวไปคูณกับหลักที่หนึ่งไล่ไปที่ละตัวแล้วบวกกัน จากกนั้นไล่ทีหลังจนหมดทีละหลังทีละแถว
    return C

In [4]:
mat1 = np.array([[1,2,3],[4,5,6]]) # 2แถว 3 หลัก
mat2 = np.array([[7,8],[9,10],[11,12]]) # 3 แถว 2 หลัก

In [5]:
mat_mul(mat1,mat2)

array([[ 58.,  64.],
       [139., 154.]])

In [6]:
mat3 = np.array([[1,2,3,4],[4,5,6,7],[2,3,4,5],[5,6,7,8]]) # 4 แถว 4 หลัก
mat4 = np.array([[5],[6],[7],[8]]) # 4 แถว 1 หลัก

In [7]:
mat_mul(mat3,mat4)

array([[ 70.],
       [148.],
       [ 96.],
       [174.]])

In [8]:
mat5 = np.array([[1,2,],[4,5,]]) # 2แถว 2 หลัก
mat6 = np.array([[7,8],[9,10],]) # 2 แถว 2 หลัก

In [9]:
mat_mul(mat5,mat6)

array([[25., 28.],
       [73., 82.]])